python twcenterpend.py 1 &
python twcenterpend.py 2 &
python twcenterpend.py 3 &
python twcenterpend.py 4 &
python twcenterpend.py 5 &
python twcenterpend.py 6 &
python twcenterpend.py 7 &
python twcenterpend.py 8 &
python twcenterpend.py 9 &
python twcenterpend.py 10 &
python twcenterpend.py 11 &
python twcenterpend.py 12 &
#python twcenterpend.py 13 &
#python twcenterpend.py 14 &
#python twcenterpend.py 15 &
#python twcenterpend.py 16 &
#python twcenterpend.py 17 &
#python twcenterpend.py 18 &
#python twcenterpend.py 19 &
#python twcenterpend.py 20 &
