python mountaincar_rllab.py 1 &
python mountaincar_rllab.py 2 &
python mountaincar_rllab.py 3 &
python mountaincar_rllab.py 4 &
python mountaincar_rllab.py 5 &
python mountaincar_rllab.py 6 &
python mountaincar_rllab.py 7 &
python mountaincar_rllab.py 8 &
python mountaincar_rllab.py 9 &
python mountaincar_rllab.py 10 &
python mountaincar_rllab.py 11 &
python mountaincar_rllab.py 12 &
#python mountaincar_rllab.py 13 &
#python mountaincar_rllab.py 14 &
#python mountaincar_rllab.py 15 &
#python mountaincar_rllab.py 16 &
#python mountaincar_rllab.py 17 &
#python mountaincar_rllab.py 18 &
#python mountaincar_rllab.py 19 &
#python mountaincar_rllab.py 20 &
