python mountaincartw.py 1 &
python mountaincartw.py 2 &
python mountaincartw.py 3 &
python mountaincartw.py 4 &
python mountaincartw.py 5 &
python mountaincartw.py 6 &
python mountaincartw.py 7 &
python mountaincartw.py 8 &
python mountaincartw.py 9 &
python mountaincartw.py 10 &
python mountaincartw.py 11 &
python mountaincartw.py 12 &
#python mountaincartw.py 13 &
#python mountaincartw.py 14 &
#python mountaincartw.py 15 &
#python mountaincartw.py 16 &
#python mountaincartw.py 17 &
#python mountaincartw.py 18 &
#python mountaincartw.py 19 &
#python mountaincartw.py 20 &
